version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  web:
    build: ./webapp
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  db-data:
